[13.0][MIG] Migrated hotel_restaurant.
OCA/vertical-hotel pull request #122
Opened 2020-09-11 12:34 UTC by dhruvitaSerpentCS

2020-09-17 07:11 UTC, Trivedi-Vacha-SerpentCS commented on hotel_restaurant/models/hotel_restaurant.py
> +
Remove blank lines

2020-09-22 15:38 UTC, vimalpatelserpentcs requested changes

2020-09-22 15:38 UTC, vimalpatelserpentcs commented on hotel_restaurant/models/hotel_restaurant.py
> +            table_ids = [tableno.id for tableno in record.table_nos_ids]
No need the for loop.
Simply use `record.table_nos_ids.ids`

2020-09-22 15:38 UTC, vimalpatelserpentcs commented on hotel_restaurant/models/hotel_restaurant.py
> +                    self.room_id = rec.folio_id.room_lines[0].product_id.id
I think no need the `for rec in self:` loop

2020-09-22 15:38 UTC, vimalpatelserpentcs commented on hotel_restaurant/models/hotel_restaurant.py
> +            table_ids = [x.id for x in order.table_nos_ids]
you can use this way as well as
`if not order_list_ids`

2020-09-22 15:38 UTC, vimalpatelserpentcs commented on hotel_restaurant/models/hotel_restaurant.py
> +            table_ids = [x.id for x in order.table_nos_ids]
No need the for loop here.
`order.table_nos_ids.ids`

2020-09-22 15:38 UTC, vimalpatelserpentcs commented on hotel_restaurant/models/hotel_restaurant.py
> +            self._context = {}
Please remove this one.
Never happen this thing

2020-09-22 15:38 UTC, vimalpatelserpentcs commented on hotel_restaurant/models/hotel_restaurant.py
> +                "kot_date": time.strftime(DEFAULT_SERVER_DATETIME_FORMAT),
Please use the fields. Date class functions here

2020-09-22 15:38 UTC, vimalpatelserpentcs commented on hotel_restaurant/models/hotel_restaurant.py
> +            table_ids = [x.id for x in order.table_nos_ids]
No need the loop here

2020-09-22 15:38 UTC, vimalpatelserpentcs commented on hotel_restaurant/models/hotel_restaurant.py
> +            table_ids = [x.id for x in order.table_nos_ids]
Same as above comment

2020-09-22 15:38 UTC, vimalpatelserpentcs commented on hotel_restaurant/models/hotel_restaurant.py
> +            self._context = {}
No need this statement

2020-09-23 06:32 UTC, vimalpatelserpentcs requested changes

2020-09-23 06:32 UTC, vimalpatelserpentcs commented on hotel_restaurant/__manifest__.py
> +        "views/hotel_restaurant_view.xml",
The report, wizard files should be after of views files

2020-09-23 06:32 UTC, vimalpatelserpentcs commented on hotel_restaurant/models/hotel_restaurant.py
> +            return True
Either use the reservation inside the loop instead of self or use self.ensure_one()
and return statement should be outside of the loop

2020-09-23 06:32 UTC, vimalpatelserpentcs commented on hotel_restaurant/models/hotel_restaurant.py
> +        if self.is_folio is True:
self.is_folio is True -> self.is_folio

2020-09-23 06:32 UTC, vimalpatelserpentcs commented on hotel_restaurant/models/hotel_restaurant.py
> +            if self.end_date > self.folio_id.room_lines.checkout_date:
If room_lines will have multiple values then will get a singleton error

2020-09-23 10:17 UTC, dhruvitaSerpentCS commented
@Trivedi-Vacha-SerpentCS, @vimalpatelserpentcs All suggested changes are done.So can you please review it?

2020-09-23 10:45 UTC, Trivedi-Vacha-SerpentCS commented on hotel_restaurant/static/description/index.html
> +<img alt="https://raw.githubusercontent.com/OCA/vertical-hotel/11.0/hotel_restaurant/static/description/res6.png" src="https://raw.githubusercontent.com/OCA/vertical-hotel/11.0/hotel_restaurant/stati
Make sure about the screenshot we attached, if the layout is different we need to update it.

2020-09-24 07:08 UTC, vimalpatelserpentcs approved these changes

2020-09-24 08:19 UTC, nikul-serpentcs reviewed
nitpicking

2020-09-24 08:19 UTC, nikul-serpentcs commented on hotel_restaurant/README.rst
> +* Serpent Consulting                Services Pvt. Ltd.
```suggestion
* Serpent Consulting Services Pvt. Ltd.
```

2020-09-24 08:19 UTC, nikul-serpentcs commented on hotel_restaurant/models/hotel_restaurant.py
> +            reservation._cr.execute(
IMO Here we need active records, so add **table_name.active='t'**

2020-09-24 08:19 UTC, nikul-serpentcs commented on hotel_restaurant/models/hotel_restaurant.py
> +        "Is a Hotel Guest??", help="is customer reside" "in hotel or not"
```suggestion
        "Is a Hotel Guest??", help="is customer reside in hotel or not"

```

2020-09-24 08:19 UTC, nikul-serpentcs commented on hotel_restaurant/models/hotel_restaurant.py
> +        "Is a Hotel Guest??", help="is customer reside" "in hotel or not"
```suggestion
        "Is a Hotel Guest??", help="is customer reside in hotel or not"
```

2020-09-24 08:19 UTC, nikul-serpentcs commented on hotel_restaurant/README.rst
> +* Odoo Community Association (OCA)
here no need to add OCA/Odoo

2020-09-24 08:19 UTC, nikul-serpentcs commented on hotel_restaurant/README.rst
> +    :target: https://github.com/OCA/vertical-hotel/tree/12.0/hotel_restaurant
```suggestion
    :target: https://github.com/OCA/vertical-hotel/tree/13.0/hotel_restaurant
```

2020-09-24 08:19 UTC, nikul-serpentcs commented on hotel_restaurant/README.rst
> +This module is part of the `OCA/vertical-hotel <https://github.com/OCA/vertical-hotel/tree/12.0/hotel_restaurant>`_ project on GitHub.
```suggestion
This module is part of the `OCA/vertical-hotel <https://github.com/OCA/vertical-hotel/tree/13.0/hotel_restaurant>`_ project on GitHub.
```

2020-09-24 09:27 UTC, Trivedi-Vacha-SerpentCS approved these changes

2020-09-24 11:26 UTC, dhruvitaSerpentCS commented on hotel_restaurant/models/hotel_restaurant.py
> +            reservation._cr.execute(
For this table, there is no active field.

2020-09-24 11:47 UTC, dhruvitaSerpentCS commented
@nikul-serpentcs Regenerated README.rst.

2020-09-25 12:51 UTC, merged