[13.0][MIG]Migrated report_hotel_reservation.
OCA/vertical-hotel pull request #128
Opened 2020-10-26 05:05 UTC by dhruvitaSerpentCS

2020-10-26 10:45 UTC, Trivedi-Vacha-SerpentCS requested changes

2020-10-26 10:45 UTC, Trivedi-Vacha-SerpentCS commented on report_hotel_reservation/README.rst
> +    :target: https://github.com/OCA/vertical-hotel/tree/12.0/report_hotel_reservation
13.0

2020-10-26 10:45 UTC, Trivedi-Vacha-SerpentCS commented on report_hotel_reservation/README.rst
> +This module is maintained by the OCA.
It should be our company details.

2020-10-26 10:45 UTC, Trivedi-Vacha-SerpentCS commented on report_hotel_reservation/README.rst
> +* Serpent Consulting                Services Pvt. Ltd.
Remove in-between space

2020-10-26 11:38 UTC, dhruvitaSerpentCS commented
@Trivedi-Vacha-SerpentCS Done all suggested changes. Can you please review it?
Thanks.

2020-10-27 05:34 UTC, vimalpatelserpentcs requested changes

2020-10-27 05:34 UTC, vimalpatelserpentcs commented on report_hotel_reservation/__manifest__.py
> +    "auto_install": False,
No need to define as false, by default it False

2020-10-27 05:34 UTC, vimalpatelserpentcs commented on report_hotel_reservation/models/report_hotel_reservation.py
> +    nbr = fields.Integer("Reservation", readonly=True)
Please change fields name `nbr -> no_of_reservation`

2020-10-27 10:39 UTC, vimalpatelserpentcs approved these changes

2020-10-27 10:50 UTC, Trivedi-Vacha-SerpentCS approved these changes

2020-10-27 12:27 UTC, merged