[14.0][MIG] hotel
OCA/vertical-hotel pull request #135
Opened 2021-01-12 09:40 UTC by kittiu

Standard migration

2021-01-21 09:36 UTC, JayVora-SerpentCS commented
@Swapnesh-SerpentCS @vimalpatelserpentcs please review.
Thanks Kitti.

2021-02-05 05:52 UTC, JayVora-SerpentCS commented
@gurneyalex Can you help us for the runbot ?

2021-02-09 17:47 UTC, Swapnesh-SerpentCS requested changes

2021-02-09 17:47 UTC, Swapnesh-SerpentCS commented on hotel/__init__.py
> +from . import wizard
```suggestion
from . import wizard
```
```suggestion
from . import wizards
```

2021-02-09 17:47 UTC, Swapnesh-SerpentCS commented on hotel/data/hotel_sequence.xml
> +    <!-- Sequences for hotel folio -->
```suggestion
    <!-- Sequence for hotel folio -->
```

2021-02-09 17:47 UTC, Swapnesh-SerpentCS commented on hotel/demo/hotel_data.xml
> +        <field eval="&quot;Ground&quot;" name="name" />
```suggestion
        <field  name="name" eval="&quot;Ground&quot;" />
```
The name should be first

2021-02-09 17:47 UTC, Swapnesh-SerpentCS commented on hotel/models/hotel_folio.py
> +def _offset_format_timestamp1(
This should not be needed now as we already have a method in odoo for this

2021-02-09 17:47 UTC, Swapnesh-SerpentCS commented on hotel/models/hotel_folio.py
> +    status = fields.Selection(string="state", related="folio_id.state")
```suggestion
    status = fields.Selection(string="State", related="folio_id.state")
```
or It should be Status

2021-02-09 17:47 UTC, Swapnesh-SerpentCS commented on hotel/models/hotel_folio.py
> +    _description = "hotel folio new"
new?

It should be Hotel Folio

2021-02-09 17:47 UTC, Swapnesh-SerpentCS commented on hotel/models/hotel_folio.py
> +        fname = ""
Unused

2021-02-09 17:47 UTC, Swapnesh-SerpentCS commented on hotel/models/hotel_folio.py
> +    def name_search(self, name="", args=None, operator="ilike", limit=100):
Not sure why this is added

2021-02-09 17:47 UTC, Swapnesh-SerpentCS commented on hotel/models/hotel_folio.py
> +                    record = line.search(
search_count

2021-02-09 17:47 UTC, Swapnesh-SerpentCS commented on hotel/models/hotel_folio.py
> +    def onchange_dates(self):
Should be Private method

2021-02-09 17:47 UTC, Swapnesh-SerpentCS commented on hotel/models/hotel_folio.py
> +            if not vals:
not needed

2021-02-09 17:47 UTC, Swapnesh-SerpentCS commented on hotel/models/hotel_folio.py
> +            h_room_obj = self.env["hotel.room"]
```suggestion
            hotel_room_obj = self.env["hotel.room"]
```

2021-02-09 17:47 UTC, Swapnesh-SerpentCS commented on hotel/models/hotel_folio.py
> +    def onchange_partner_id(self):
Should be Private method

2021-02-09 17:47 UTC, Swapnesh-SerpentCS commented on hotel/models/hotel_folio.py
> +            self.update(
ValidationError should not be in Onchange

2021-02-09 17:47 UTC, Swapnesh-SerpentCS commented on hotel/models/hotel_folio.py
> +        for order in self.order_id:
order_id will be a single record so no need to iterate loop

2021-02-09 17:47 UTC, Swapnesh-SerpentCS commented on hotel/models/hotel_folio.py
> +    def action_cancel_draft(self):
Not sure What is does looking at Method name

2021-02-09 17:47 UTC, Swapnesh-SerpentCS commented on hotel/models/hotel_folio.py
> +            return self._context["checkin"]
return self._context["checkin"] or time.strftime(DEFAULT_SERVER_DATETIME_FORMAT)

2021-02-15 13:48 UTC, vimalpatelserpentcs requested changes

2021-02-15 13:48 UTC, vimalpatelserpentcs commented on hotel/models/hotel_folio.py
> +            to_zone = "UTC"
we can make it in single line
to_zone = self._context.get("tz", "UTC")

2021-02-15 13:48 UTC, vimalpatelserpentcs commented on hotel/models/hotel_folio.py
> +            rooms_list = [res.product_id.id for res in rec.room_line_ids]
Here we can use mapped function
rooms_list = rec.room_line_ids.mapped('product_id').ids

2021-02-15 13:48 UTC, vimalpatelserpentcs commented on hotel/models/hotel_folio.py
> +                    room_obj = h_room_obj.search([("name", "=", rm.name)])
If room_list is products objects then here we need to use rm.product_id.id instead of search with name

2021-02-15 13:48 UTC, vimalpatelserpentcs commented on hotel/models/hotel_folio.py
> +            order_ids = [folio.order_id.id for folio in self]
Nice to have to use mapped instead of for loop

2021-02-15 13:48 UTC, vimalpatelserpentcs commented on hotel/models/hotel_folio.py
> +        return True
We can optimise this code as well as.

self.mapped('order_line_id').button_done()
self.write({"state": "done"})

2021-02-26 07:24 UTC, gurneyalex commented
> @gurneyalex Can you help us for the runbot ?

In this specific case, the issue is not with runbot, it's with the PR. Runbot is red because of a view which cannot be installed (hotel_room.xml specifies a rental field which does not exist). This also causes a red build on travis (https://travis-ci.com/github/OCA/vertical-hotel/jobs/473760498#L1456), so fix these issues on the PR and things should get better.

2021-07-27 08:44 UTC, flotho commented
Hi,

AFAICS, this PR seems useless because the hotel module is already present in v14.

Am I right

Regards

2021-07-28 12:59 UTC, JayVora-SerpentCS commented
yes its deprecated.
@kittiu does always good.
Thanks.

2021-07-28 12:59 UTC, closed without merging