Hotel reservation mig v14
OCA/vertical-hotel pull request #146
Opened 2021-05-18 10:20 UTC by maitripatel19

Hotel reservation mig v14

2021-05-31 05:57 UTC, Trivedi-Vacha-SerpentCS requested changes

2021-05-31 05:57 UTC, Trivedi-Vacha-SerpentCS commented on hotel_reservation/LICENSE/LICENSE
> +    Copyright (C) 2020-TODAY Serpent Consulting Services Pvt. Ltd. (<http://www.serpentcs.com>).
```suggestion
    Copyright (C) 2021-TODAY Serpent Consulting Services Pvt. Ltd. (<http://www.serpentcs.com>).
```

2021-05-31 05:57 UTC, Trivedi-Vacha-SerpentCS commented on hotel_reservation/README.rst
> +* Serpent Consulting                 Services Pvt. Ltd.
```suggestion
* Serpent Consulting Services Pvt. Ltd.
```

2021-05-31 05:57 UTC, Trivedi-Vacha-SerpentCS commented on hotel_reservation/__manifest__.py
> +        "data/email_template_view.xml",
Define data file before views

2021-05-31 05:57 UTC, Trivedi-Vacha-SerpentCS commented on hotel_reservation/models/hotel_quick_reservation.py
> +            if self.check_out < self.check_in:
Combine both condition
```suggestion
            if (self.check_out and self.check_in) and (self.check_out < self.check_in):
```

2021-06-02 18:35 UTC, JayVora-SerpentCS requested changes

2021-06-02 18:35 UTC, JayVora-SerpentCS commented on hotel_reservation/README.rst
> +    :target: https://runbot.odoo-community.org/runbot/157/13.0
Check this PATH of IMAGES above and runbot v14 every PR

2021-06-02 18:35 UTC, JayVora-SerpentCS commented on hotel_reservation/data/hotel_reservation_data.xml
> +        <field eval="&quot;2018-05-02 12:09:00&quot;" name="checkin" />
make them 2021 for v14

2021-06-02 18:35 UTC, JayVora-SerpentCS commented on hotel_reservation/i18n/zh_CN.po
> +# Translation of Odoo Server.
You have to regenerate PO files. @Swapnesh-SerpentCS will guide.

2021-06-02 18:35 UTC, JayVora-SerpentCS commented on hotel_reservation/models/hotel_folio.py
> +        res = super(HotelFolio, self).write(vals)
I am unable to understand the need of this code. @vimalpatelserpentcs can you identify?

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/README.rst
> +    :target: https://runbot.odoo-community.org/runbot/157/13.0
@maitripatel19 , Please use `oca-gen-addon-readme` command for Readme file
ref: https://github.com/OCA/maintainer-tools/blob/master/README.md

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/data/hotel_reservation_data.xml
> +<?xml version="1.0" encoding="utf-8" ?>
No need this line

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/data/hotel_reservation_data.xml
> +        <field eval="&quot;2018-05-02 10:00:00&quot;" name="date_order" />
```suggestion
        <field eval="(DateTime.today()).strftime('%Y-%m-%d 10:00:00')" name="date_order"/>
```

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/data/hotel_scheduler.xml
> +        <field name="name">Inform Guest About Reservation Before 24 Hours
```suggestion
        <field name="name">Hotel Reservation: Booking Reminder before 24 Hours
```

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_folio.py
> +        res = super(HotelFolio, self).write(vals)
Yes, If it is folio created from reservation then the system will update the room reservation line status

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_folio.py
> +                if line.status != "cancel":
Instead of the condition, please add a filtered function to avoid the extra looping

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_folio.py
> +        chkout = vals.get("checkout_date") or self.checkout_date
please set proper variable name

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_folio.py
> +                    if rm_lines:
No need this condition

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_quick_reservation.py
> +    def on_change_check_out(self):
please make this method as private

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_quick_reservation.py
> +                                "reserve": [(6, 0, [res.room_id.id])],
```suggestion
                                "reserve": [(6, 0, res.room_id.ids)],
```

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_quick_reservation.py
> +                                "name": (res.room_id and res.room_id.name or ""),
```suggestion
                                "name": res.room_id.name or " ",
```

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_reservation.py
> +class HotelFolioLineExt(models.Model):
```suggestion
class HotelFolioLine(models.Model):
```

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_reservation.py
> +    def on_change_checkout(self):
Please make this method as private

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_reservation.py
> +    reservation_no = fields.Char("Reservation No", readonly=True)
```suggestion
    reservation_no = fields.Char("Reservation No", readonly=True, copy=False)
```

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_reservation.py
> +    )
We need to remove the warehouse_id(stock.warehouse), Please add company_id(res.company) fields instead of warehouse_id

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_reservation.py
> +        default=lambda *a: "draft",
```suggestion
        default="draft",
```

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_reservation.py
> +    no_of_folio = fields.Integer("No. Folio", compute="_compute_folio_id")
```suggestion
    no_of_folio = fields.Integer("No. Folio", compute="_compute_folio_count")
```

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_reservation.py
> +    def _compute_folio_id(self):
```suggestion
    def _compute_folio_count(self):
```

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_reservation.py
> +            if reserv_rec.state != "draft":
instead of if condition, add filtered function

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_reservation.py
> +    def check_reservation_rooms(self):
should be private method

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_reservation.py
> +    def onchange_partner_id(self):
should be private method

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_reservation.py
> +            reservation_line.reserve.write({"isroom": True, "status": "available"})
```suggestion
        reservation_lines.mapped('reserve').write({"isroom": True, "status": "available"})
```

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_reservation.py
> +    _name = "hotel_reservation.line"
```suggestion
    _name = "hotel.reservation.line"
```

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_reservation.py
> +    def on_change_categ(self):
```suggestion
    def _onchange_category(self):
```

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_reservation.py
> +                if line.status != "cancel":
instead of if condition please use filtered on loop

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_reservation.py
> +                if myobj:
No need this condition

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_reservation.py
> +        curr_date = now.strftime(dt)
No need to convert datetime to string

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_reservation.py
> +            ]
```suggestion
            reserv_line_ids = room.room_reservation_line_ids.mapped('reservation_line').ids
```

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_reservation.py
> +            rooms_ids = [room_line.id for room_line in room.room_line_ids]
Use the mapped function

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_reservation.py
> +            )
I think no need for conversion, please use odoo based timestamp method

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/models/hotel_room.py
> +                if reserv_line.status == "confirm":
use the filtered function

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/report/checkin_report_template.xml
> +<?xml version="1.0" encoding="utf-8" ?>
no need this line

2021-06-03 10:18 UTC, vimalpatelserpentcs commented on hotel_reservation/report/report_view.xml
> +        id="hotel_checkin_details"
remove the commented code

2021-08-09 08:10 UTC, merged