[14.0][ADD] hotel_housekeeping: Migrated  module.
OCA/vertical-hotel pull request #148
Opened 2021-05-19 05:07 UTC by maitripatel19

[14.0][ADD] hotel_housekeeping: Migrated  module.

2021-05-31 05:49 UTC, Trivedi-Vacha-SerpentCS requested changes

2021-05-31 05:49 UTC, Trivedi-Vacha-SerpentCS commented on hotel_housekeeping/report/activity_detail.rml
> +  <template pageSize="(595.0,842.0)" title="Test" author="Martin Simon" allowSplitting="20">
why rml file added??

2021-05-31 12:46 UTC, vimalpatelserpentcs commented
@maitripatel19 @Trivedi-Vacha-SerpentCS , Travis is failed, I think you missed installing pre-commit. Can you please check that? Thank you.

2021-06-01 10:14 UTC, nikul-serpentcs requested changes
nitpicking

2021-06-01 10:14 UTC, nikul-serpentcs commented on hotel_housekeeping/README.rst
> +    :target: https://github.com/OCA/vertical-hotel/tree/13.0/hotel_housekeeping
```suggestion
    :target: https://github.com/OCA/vertical-hotel/tree/14.0/hotel_housekeeping
```

2021-06-01 10:14 UTC, nikul-serpentcs commented on hotel_housekeeping/README.rst
> +    :target: https://translation.odoo-community.org/projects/vertical-hotel-13-0/vertical-hotel-13-0-hotel_housekeeping
```suggestion
    :target: https://translation.odoo-community.org/projects/vertical-hotel-14-0/vertical-hotel-14-0-hotel_housekeeping
```

2021-06-01 10:14 UTC, nikul-serpentcs commented on hotel_housekeeping/README.rst
> +* Serpent Consulting                Services Pvt. Ltd.
```suggestion
* Serpent Consulting Services Pvt. Ltd.
```

2021-06-02 17:51 UTC, JayVora-SerpentCS requested changes

2021-06-02 17:51 UTC, JayVora-SerpentCS commented on hotel_housekeeping/README.rst
> +    .. image:: https://raw.githubusercontent.com/OCA/vertical-hotel/11.0/hotel_housekeeping/static/description/HHK1.png
Path is still 11.0

2021-06-02 17:51 UTC, JayVora-SerpentCS commented on hotel_housekeeping/models/hotel_housekeeping.py
> +        help="Detail of housekeeping \
please do pep-8 right.
Please check and do with https://github.com/OCA/maintainer-tools#developers
Thanks,

2021-06-02 17:51 UTC, JayVora-SerpentCS commented on hotel_housekeeping/models/hotel_housekeeping.py
> +        help="Detail of housekeeping \
Do this for all other PRs. thank you for the good work.

2021-06-02 17:51 UTC, JayVora-SerpentCS commented on hotel_housekeeping/models/hotel_housekeeping.py
> +        self.write({"state": "dirty", "quality": False})
'Quality' selection does not not need to pass False if nothing is set. Did you check its impact ?

2021-08-12 09:21 UTC, merged