[15.0][MIG]hotel_restaurant
OCA/vertical-hotel pull request #176
Opened 2022-10-07 06:44 UTC by ShwetaSerpentCS

2022-10-10 12:01 UTC, uncannycs requested changes
Fix mention comments and good to go

2022-10-10 12:01 UTC, uncannycs commented on hotel_restaurant/LICENSE/LICENSE
> +    Copyright (C) 2021-TODAY Serpent Consulting Services Pvt. Ltd. (<http://www.serpentcs.com>).
Year should be 2022

2022-10-10 12:01 UTC, uncannycs commented on hotel_restaurant/LICENSE/LICENSE
> +    it under the terms of the GNU Affero General Public License as
Can we use a V15 level licence file?

2022-10-10 12:01 UTC, uncannycs commented on hotel_restaurant/README.rst
> +    :target: https://github.com/OCA/vertical-hotel/tree/14.0/hotel_restaurant
version should be v15

2022-10-10 12:01 UTC, uncannycs commented on hotel_restaurant/README.rst
> +    :target: https://runbot.odoo-community.org/runbot/157/14.0
Check entire this file and make version changes from 14.0 to 15.0

2022-10-10 12:01 UTC, uncannycs commented on hotel_restaurant/__manifest__.py
> +    "version": "15.0.1.0.0",
Initial version should be start from the 0

2022-11-30 10:36 UTC, JayVora-SerpentCS commented
@ShwetaSerpentCS pls update.

2023-03-06 13:34 UTC, ShwetaSerpentCS commented on hotel_restaurant/__manifest__.py
> +    "version": "15.0.1.0.0",
@uncannycs I followed version based on OCA Guidelines https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#version-numbers

2023-03-14 10:27 UTC, ShwetaSerpentCS commented
@JayVora-SerpentCS @murtuzasaleh This PR is ready for review.

2023-03-14 10:54 UTC, ShwetaSerpentCS commented
> @JayVora-SerpentCS @murtuzasaleh This PR is ready for review.

@nikul-serpentcs

2023-04-06 14:50 UTC, merged