[MIG] hotel_reservation: Migration to 11.0
OCA/vertical-hotel pull request #34
Opened 2018-04-23 11:41 UTC by KrishnaPrajapati-SerpentCS

2018-05-17 14:40 UTC, JayVora-SerpentCS requested changes

2018-05-17 14:40 UTC, JayVora-SerpentCS commented on hotel_reservation/README.rst
> +==================
Align = with n.

2018-05-17 14:40 UTC, JayVora-SerpentCS commented on hotel_reservation/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/157/10.0
11.0

2018-07-31 08:07 UTC, darshan-serpent commented
Supersedes Now with #42

2018-07-31 08:08 UTC, closed without merging

2018-09-03 06:07 UTC, vbezl commented on hotel_reservation/static/src/js/hotel_room_summary.js
> +         form_common.ReinitializeWidgetMixin.initialize_field.call(this);
no declaration of form_common

2018-09-03 06:07 UTC, vbezl commented on hotel_reservation/static/src/js/hotel_room_summary.js
> +        this.on("_onFieldChanged:date_from", this, function() {
this doesn't work for some reason - nothing is printed to console when changing date_from