[MIG] report_hotel_restaurant: Migration to 11.0
OCA/vertical-hotel pull request #38
Opened 2018-04-24 07:17 UTC by KrishnaPrajapati-SerpentCS

2018-05-17 23:14 UTC, omarouhari approved these changes

2018-05-21 08:20 UTC, JayVora-SerpentCS approved these changes

2018-05-21 08:22 UTC, omarouhari approved these changes

2018-07-31 13:29 UTC, serpentcs-dev1 approved these changes
Technical Review LGTM +1

2018-07-31 13:36 UTC, JayVora-SerpentCS requested changes

2018-07-31 13:36 UTC, JayVora-SerpentCS commented on report_hotel_restaurant/__manifest__.py
> +    'website': 'http://www.serpentcs.com',
website : https://github.com/OCA/vertical-hotel

2018-10-01 07:55 UTC, JayVora-SerpentCS approved these changes

2018-10-01 07:55 UTC, merged